#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define LIM_NOME 20
#define MAX_UC 40
#define MAX_ESTUDANTES 100
#define MAX_AULAS 300
#define MAX_STRING 50
#define MENU_UCS 1
#define MENU_AULAS 2
#define MENU_ESTUDANTES 3
#define MENU_ESTATISTICA 4
#define MENU_BINARIOS 5
#define INSERIR 1
#define ALTERAR 2
#define INICIAR 3
#define ACABAR 4
#define LISTAR_AULAS 5
#define APRESENTAR 6
#define FICHEIROS_AULAS 7
#define LISTAR_UC 3
#define FICHEIROS_UC 4
#define ESCREVER_BIN 1
#define LER_BIN 2
#define MENU_AGENDADAS 1
#define SAIR_MENU 0
#define OBRIGATORIA 1
#define T 1
#define TP 2
#define PL 3
#define DIURNO 1
#define POS_LABORAL 2
#define MIN_ANO 2000
#define MAX_ANO 2500
#define JANEIRO 1
#define FEVEREIRO 2
#define MARCO 3
#define ABRIL 4
#define MAIO 5
#define JUNHO 6
#define JULHO 7
#define AGOSTO 8
#define SETEMBRO 9
#define OUTUBRO 10
#define NOVEMBRO 11
#define DEZEMBRO 12
#define DIAS30 30
#define DIAS31 31
#define MAX_DIA_FEVEREIRO 28
#define MAX_DIA_FEVEREIRO_BISSEXTO 29
#define MIN_DIURNO 8
#define MAX_DIURNO 18
#define MAX_POSLABORAL 24
#define MIN_MINUTOS 0
#define MAX_MINUTOS 59
#define UMA_HORA_EM_MINUTOS 60
#define AGENDADA 1
#define A_DECORRER 2
#define REALIZADA 3
#define ONLINE 1
#define OFFLINE 2

#endif // CONSTANTES_H_INCLUDED
